{
    "question": "How can I run a SQL file in psql and get error messages with line numbers?",
    "expected_answer": "You can use the -f option to run a SQL file, which provides error messages with line numbers and may reduce start-up overhead compared to input redirection. Using psql -f filename enables these features.",
    "source_chunk_id": "app-psql.html_4",
    "acceptable_chunk_ids": [
      "app-psql.html_3",
      "app-psql.html_4",
      "app-psql.html_5"
    ],
    "source_chunk_content": "Using this option is subtly different from writing `psql\n    < filename`. In general,\n    both will do what you expect, but using `-f`\n    enables some nice features such as error messages with line\n    numbers. There is also a slight chance that using this option will\n    reduce the start-up overhead. On the other hand, the variant using\n    the shell's input redirection is (in theory) guaranteed to yield\n    exactly the same output you would have received had you entered\n    everything by hand.\n\n`-F separator`\\ `--field-separator=separator` \n:   Use *`separator`* as the\n    field separator for unaligned output. This is equivalent to\n    `\\pset fieldsep` or `\\f`.\n\n`-h hostname`\\ `--host=hostname` \n:   Specifies the host name of the machine on which the\n    server is running. If the value begins\n    with a slash, it is used as the directory for the Unix-domain\n    socket.\n\n`-H`\\ `--html` \n:   Switches to HTML output mode. This is\n    equivalent to `\\pset format html` or the\n    `\\H` command.\n\n`-l`\\ `--list` \n:   List all available databases, then exit. Other non-connection\n    options are ignored. This is similar to the meta-command\n    `\\list`.",
    "source_file": "app-psql.html",
    "source_title": "psql",
    "source_url": "https://www.postgresql.org/docs/16/app-psql.html",
    "token_count": 291,
    "_valid": true,
    "_validation_reason": "The excerpt explicitly states that using the -f option to run a SQL file enables error messages with line numbers, answering the question fully and correctly."
  },

{
    "id": "app-psql.html_4",
    "source": "app-psql.html",
    "title": "psql",
    "content": "Using this option is subtly different from writing `psql\n    < filename`. In general,\n    both will do what you expect, but using `-f`\n    enables some nice features such as error messages with line\n    numbers. There is also a slight chance that using this option will\n    reduce the start-up overhead. On the other hand, the variant using\n    the shell's input redirection is (in theory) guaranteed to yield\n    exactly the same output you would have received had you entered\n    everything by hand.\n\n`-F separator`\\ `--field-separator=separator` \n:   Use *`separator`* as the\n    field separator for unaligned output. This is equivalent to\n    `\\pset fieldsep` or `\\f`.\n\n`-h hostname`\\ `--host=hostname` \n:   Specifies the host name of the machine on which the\n    server is running. If the value begins\n    with a slash, it is used as the directory for the Unix-domain\n    socket.\n\n`-H`\\ `--html` \n:   Switches to HTML output mode. This is\n    equivalent to `\\pset format html` or the\n    `\\H` command.\n\n`-l`\\ `--list` \n:   List all available databases, then exit. Other non-connection\n    options are ignored. This is similar to the meta-command\n    `\\list`.",
    "token_count": 291,
    "type": "text_block"
  },

{
    "question": "How does PostgreSQL decide which function version to call when using a variadic function with different argument types?",
    "expected_answer": "PostgreSQL will choose a more specific function that exactly matches the argument type if available. For example, if you have both a variadic function accepting numeric[] and functions specifically for numeric or int, calls with single int or numeric arguments will prefer the exact-match functions, while only the call with the VARIADIC keyword and an array argument will use the variadic function. This behavior affects security because the generic calls could be intercepted by newly created specific-type functions.",
    "source_chunk_id": "typeconv-func.html_6",
    "acceptable_chunk_ids": [
      "typeconv-func.html_5",
      "typeconv-func.html_6",
      "typeconv-func.html_7"
    ],
    "source_chunk_content": "Note that the “best match” rules are identical for operator and\nfunction type resolution.\nSome examples follow.\n\n**Example 10.6. Rounding Function Argument Type Resolution**\n\nThere is only one `round` function that takes two\narguments; it takes a first argument of type `numeric` and\na second argument of type `integer`.\nSo the following query automatically converts\nthe first argument of type `integer` to\n`numeric`:\n\n```sql\nSELECT round(4, 4);\n\n round\n--------\n 4.0000\n(1 row)\n```\n\nThat query is actually transformed by the parser to:\n\n```sql\nSELECT round(CAST (4 AS numeric), 4);\n```\n\nSince numeric constants with decimal points are initially assigned the\ntype `numeric`, the following query will require no type\nconversion and therefore might be slightly more efficient:\n\n```sql\nSELECT round(4.0, 4);\n```\n\n\\\n\n**Example 10.7. Variadic Function Resolution**\n\n```sql\nCREATE FUNCTION public.variadic_example(VARIADIC numeric[]) RETURNS int\n  LANGUAGE sql AS 'SELECT 1';\nCREATE FUNCTION\n```\n\nThis function accepts, but does not require, the VARIADIC keyword. It\ntolerates both integer and numeric arguments:\n\n```sql\nSELECT public.variadic_example(0),\n       public.variadic_example(0.0),\n       public.variadic_example(VARIADIC array[0.0]);\n variadic_example | variadic_example | variadic_example\n------------------+------------------+------------------\n                1 |                1 |                1\n(1 row)\n```\n\nHowever, the first and second calls will prefer more-specific functions, if\navailable:\n\n```sql\nCREATE FUNCTION public.variadic_example(numeric) RETURNS int\n  LANGUAGE sql AS 'SELECT 2';\nCREATE FUNCTION\n\nCREATE FUNCTION public.variadic_example(int) RETURNS int\n  LANGUAGE sql AS 'SELECT 3';\nCREATE FUNCTION\n\nSELECT public.variadic_example(0),\n       public.variadic_example(0.0),\n       public.variadic_example(VARIADIC array[0.0]);\n variadic_example | variadic_example | variadic_example\n------------------+------------------+------------------\n                3 |                2 |                1\n(1 row)\n```\n\nGiven the default configuration and only the first function existing, the\nfirst and second calls are insecure. Any user could intercept them by\ncreating the second or third function. By matching the argument type exactly\nand using the `VARIADIC` keyword, the third call is secure.\n\n\\\n\n**Example 10.8. Substring Function Type Resolution**\n\nThere are several `substr` functions, one of which\ntakes types `text` and `integer`. If called\nwith a string constant of unspecified type, the system chooses the\ncandidate function that accepts an argument of the preferred category\n`string` (namely of type `text`).\n\n```sql\nSELECT substr('1234', 3);\n\n substr\n--------\n     34\n(1 row)\n```",
    "source_file": "typeconv-func.html",
    "source_title": "10.3. Functions",
    "source_url": "https://www.postgresql.org/docs/16/typeconv-func.html",
    "token_count": 640,
    "_valid": true,
    "_validation_reason": "The excerpt explicitly explains how PostgreSQL selects more-specific functions for exact argument type matches over generic variadic functions and illustrates this with examples and security implications."
  },
{
    "id": "typeconv-func.html_6",
    "source": "typeconv-func.html",
    "title": "10.3. Functions",
    "content": "Note that the “best match” rules are identical for operator and\nfunction type resolution.\nSome examples follow.\n\n**Example 10.6. Rounding Function Argument Type Resolution**\n\nThere is only one `round` function that takes two\narguments; it takes a first argument of type `numeric` and\na second argument of type `integer`.\nSo the following query automatically converts\nthe first argument of type `integer` to\n`numeric`:\n\n```sql\nSELECT round(4, 4);\n\n round\n--------\n 4.0000\n(1 row)\n```\n\nThat query is actually transformed by the parser to:\n\n```sql\nSELECT round(CAST (4 AS numeric), 4);\n```\n\nSince numeric constants with decimal points are initially assigned the\ntype `numeric`, the following query will require no type\nconversion and therefore might be slightly more efficient:\n\n```sql\nSELECT round(4.0, 4);\n```\n\n\\\n\n**Example 10.7. Variadic Function Resolution**\n\n```sql\nCREATE FUNCTION public.variadic_example(VARIADIC numeric[]) RETURNS int\n  LANGUAGE sql AS 'SELECT 1';\nCREATE FUNCTION\n```\n\nThis function accepts, but does not require, the VARIADIC keyword. It\ntolerates both integer and numeric arguments:\n\n```sql\nSELECT public.variadic_example(0),\n       public.variadic_example(0.0),\n       public.variadic_example(VARIADIC array[0.0]);\n variadic_example | variadic_example | variadic_example\n------------------+------------------+------------------\n                1 |                1 |                1\n(1 row)\n```\n\nHowever, the first and second calls will prefer more-specific functions, if\navailable:\n\n```sql\nCREATE FUNCTION public.variadic_example(numeric) RETURNS int\n  LANGUAGE sql AS 'SELECT 2';\nCREATE FUNCTION\n\nCREATE FUNCTION public.variadic_example(int) RETURNS int\n  LANGUAGE sql AS 'SELECT 3';\nCREATE FUNCTION\n\nSELECT public.variadic_example(0),\n       public.variadic_example(0.0),\n       public.variadic_example(VARIADIC array[0.0]);\n variadic_example | variadic_example | variadic_example\n------------------+------------------+------------------\n                3 |                2 |                1\n(1 row)\n```\n\nGiven the default configuration and only the first function existing, the\nfirst and second calls are insecure. Any user could intercept them by\ncreating the second or third function. By matching the argument type exactly\nand using the `VARIADIC` keyword, the third call is secure.\n\n\\\n\n**Example 10.8. Substring Function Type Resolution**\n\nThere are several `substr` functions, one of which\ntakes types `text` and `integer`. If called\nwith a string constant of unspecified type, the system chooses the\ncandidate function that accepts an argument of the preferred category\n`string` (namely of type `text`).\n\n```sql\nSELECT substr('1234', 3);\n\n substr\n--------\n     34\n(1 row)\n```",
    "token_count": 640,
    "type": "text_block"
  },